from fpdf import FPDF
import tempfile
import os
import datetime

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'Lintarix AI - Investment Analysis Report', 0, 1, 'C')
        self.line(10, 20, 200, 20)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by Lintarix AI', 0, 0, 'C')

def create_pdf(ticker, summary, analysis_text, chart_fig):
    """
    Fungsi utama untuk membuat PDF.
    Menerima: Ticker, Data Summary, Teks AI, dan Objek Grafik Plotly.
    Output: Bytes PDF (siap didownload).
    """
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- 1. HEADER INFO ---
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, f"Ticker: {ticker}", ln=True)
    pdf.set_font("Arial", "", 10)
    pdf.cell(0, 5, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.ln(5)

    # --- 2. KEY METRICS (Grid Layout) ---
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Arial", "B", 10)
    
    # Baris 1
    pdf.cell(45, 8, "Current Price", 1, 0, 'C', 1)
    pdf.cell(45, 8, "RSI (14)", 1, 0, 'C', 1)
    pdf.cell(45, 8, "Trend", 1, 0, 'C', 1)
    pdf.cell(45, 8, "Volume", 1, 1, 'C', 1) # Pindah baris
    
    # Isi Data
    pdf.set_font("Arial", "", 10)
    pdf.cell(45, 8, f"{summary['current_price']:,}", 1, 0, 'C')
    pdf.cell(45, 8, str(summary['rsi']), 1, 0, 'C')
    pdf.cell(45, 8, summary['trend'], 1, 0, 'C')
    pdf.cell(45, 8, f"{summary['volume']:,}", 1, 1, 'C')
    pdf.ln(10)

    # --- 3. CHART IMAGE ---
    # Plotly harus disimpan jadi PNG dulu baru bisa masuk PDF
    try:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmpfile:
            # Simpan grafik ke file temporary
            chart_fig.write_image(tmpfile.name, width=800, height=400)
            
            # Masukkan ke PDF
            pdf.image(tmpfile.name, x=10, w=190) # Lebar 190mm (full width A4)
            tmp_filename = tmpfile.name
        
        # Hapus file temporary setelah dipakai
        os.unlink(tmp_filename)
        pdf.ln(5)
    except Exception as e:
        pdf.set_text_color(255, 0, 0)
        pdf.cell(0, 10, f"Error generating chart image: {str(e)}", ln=True)
        pdf.set_text_color(0, 0, 0)

    # --- 4. AI ANALYSIS TEXT ---
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "AI Reasoning & Analysis", ln=True)
    pdf.ln(2)

    pdf.set_font("Arial", "", 11)
    
    # Membersihkan Markdown sederhana karena FPDF tidak support Bold via **text**
    # dan menghapus Emoji (sering bikin error encoding di PDF standar)
    clean_text = analysis_text.replace("**", "").replace("#", "")
    clean_text = clean_text.encode('latin-1', 'replace').decode('latin-1') 

    # Multi_cell otomatis wrap text ke baris baru
    pdf.multi_cell(0, 6, clean_text)
    
    # Return sebagai string binary untuk tombol download
    return pdf.output(dest='S').encode('latin-1')